// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/login/phone_login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登录模块"
                ],
                "summary": "手机号登录",
                "parameters": [
                    {
                        "description": " ",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginApiPhoneLoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"dm_error\":0,\"error_msg\":\"\",\"data\":{}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/profile/detail": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户资料模块"
                ],
                "summary": "获取个人信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ProfileApiDetailResp"
                        }
                    }
                }
            }
        },
        "/api/profile/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户资料模块"
                ],
                "summary": "更新个人信息",
                "parameters": [
                    {
                        "description": " ",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ProfileApiUpdateRep"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"dm_error\":0,\"error_msg\":\"\",\"data\":{}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user_login/sing_up": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登录模块"
                ],
                "summary": "微信登录",
                "parameters": [
                    {
                        "description": " ",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginApiWeChatLoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"dm_error\":0,\"error_msg\":\"\",\"data\":{}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.LoginApiPhoneLoginReq": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "passport": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "password2": {
                    "type": "string"
                }
            }
        },
        "model.LoginApiWeChatLoginReq": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "model.ProfileApiDetailResp": {
            "type": "object",
            "properties": {
                "birth": {
                    "description": "生日",
                    "type": "integer"
                },
                "gender": {
                    "description": "性别 1-男；2-女",
                    "type": "integer"
                },
                "hometown": {
                    "description": "家乡",
                    "type": "string"
                },
                "name": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "passport": {
                    "description": "用户账号",
                    "type": "string"
                },
                "phone": {
                    "description": "手机",
                    "type": "string"
                },
                "portrait": {
                    "description": "头像",
                    "type": "string"
                },
                "uid": {
                    "description": "用户ID",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "model.ProfileApiUpdateRep": {
            "type": "object",
            "required": [
                "birth"
            ],
            "properties": {
                "birth": {
                    "description": "必填 生日",
                    "type": "integer"
                },
                "gender": {
                    "description": "必填 性别",
                    "type": "integer"
                },
                "hometown": {
                    "description": "家乡",
                    "type": "string"
                },
                "name": {
                    "description": "必填 用户昵称",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "portrait": {
                    "description": "头像",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "39.108.101.229:80",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "用户服务",
	Description: "用户服务 API 文档.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
